// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5KVKKzw7maO5HpLfAwBc_yQJcKPoTcxU',
    appId: '1:106663376783:web:659f28300347910d1abdfa',
    messagingSenderId: '106663376783',
    projectId: 'kinetic-folio-2p425',
    authDomain: 'kinetic-folio-2p425.firebaseapp.com',
    storageBucket: 'kinetic-folio-2p425.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7RSu3LrCeDJgvsXbfOY3io3bYLud5WOY',
    appId: '1:106663376783:android:7716d2c6f34772881abdfa',
    messagingSenderId: '106663376783',
    projectId: 'kinetic-folio-2p425',
    storageBucket: 'kinetic-folio-2p425.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXBH8x9YptVkjTEHQ8I24vrOlWxsX1tl8',
    appId: '1:106663376783:ios:d3956982183127db1abdfa',
    messagingSenderId: '106663376783',
    projectId: 'kinetic-folio-2p425',
    storageBucket: 'kinetic-folio-2p425.firebasestorage.app',
    iosBundleId: 'com.example.daypilot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXBH8x9YptVkjTEHQ8I24vrOlWxsX1tl8',
    appId: '1:106663376783:ios:d3956982183127db1abdfa',
    messagingSenderId: '106663376783',
    projectId: 'kinetic-folio-2p425',
    storageBucket: 'kinetic-folio-2p425.firebasestorage.app',
    iosBundleId: 'com.example.daypilot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5KVKKzw7maO5HpLfAwBc_yQJcKPoTcxU',
    appId: '1:106663376783:web:c6edd832b98f893f1abdfa',
    messagingSenderId: '106663376783',
    projectId: 'kinetic-folio-2p425',
    authDomain: 'kinetic-folio-2p425.firebaseapp.com',
    storageBucket: 'kinetic-folio-2p425.firebasestorage.app',
  );

}